# Generated by Django 5.0.6 on 2024-06-30 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweet", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tweet",
            old_name="tweet",
            new_name="text",
        ),
    ]
